exports.SUPER_ADMIN = "SUPER_ADMIN";
exports.ADMIN = "ADMIN";
exports.USER = "USER";

exports.ROLES = [exports.SUPER_ADMIN, exports.ADMIN, exports.USER];

const OAUTH_PROVIDERS = {
  EMAIL: "EMAIL",
  GOOGLE: "GOOGLE",
  FACEBOOK: "FACEBOOK",
  APPLE: "APPLE",
};
exports.OAUTH_PROVIDERS = OAUTH_PROVIDERS;


exports.CLASSES = ["FIRST_SECONDARY", "SECOND_SECONDARY", "THIRD_SECONDARY"]
exports.STUDY_MODES = ["ONLINE", "CENTER"]
exports.COURSE_LEVELS = ["NORMAL", "INTERMEDIATE", "ADVANCED", "NORMAL"]