exports.SUPER_ADMIN = "SUPER_ADMIN";
exports.ADMIN = "ADMIN";
exports.USER = "USER";

exports.ROLES = [exports.SUPER_ADMIN, exports.ADMIN, exports.USER];

exports.LOGIN_TYPE = ["EMAIL", "GOOGLE", "FACEBOOK", "APPLE"]; 

const OAUTH_PROVIDERS = {
  EMAIL: "EMAIL",
  GOOGLE: "GOOGLE",
  FACEBOOK: "FACEBOOK",
  APPLE: "APPLE",
};
exports.OAUTH_PROVIDERS = OAUTH_PROVIDERS;

exports.COURSE_LEVELS = ["NORMAL", "INTERMEDIATE", "ADVANCED", "NORMAL"]